# Generated by Django 4.0.2 on 2022-08-03 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_booking_tod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ToD',
            field=models.TimeField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
