# Generated by Django 4.0.2 on 2022-08-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0006_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_time']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
    ]
