# Generated by Django 4.0.2 on 2022-07-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0007_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
    ]
